# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/comicdl.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_comicdl(object):
    def setupUi(self, comicdl):
        comicdl.setObjectName("comicdl")
        comicdl.resize(426, 260)
        self.centralwidget = QtWidgets.QWidget(comicdl)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.fromch = QtWidgets.QLineEdit(self.centralwidget)
        self.fromch.setObjectName("fromch")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fromch)
        self.toch = QtWidgets.QLineEdit(self.centralwidget)
        self.toch.setObjectName("toch")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.toch)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 2)
        comicdl.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(comicdl)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 426, 25))
        self.menubar.setObjectName("menubar")
        self.menuComic_DL = QtWidgets.QMenu(self.menubar)
        self.menuComic_DL.setObjectName("menuComic_DL")
        comicdl.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(comicdl)
        self.statusbar.setObjectName("statusbar")
        comicdl.setStatusBar(self.statusbar)
        self.actionSetting = QtWidgets.QAction(comicdl)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtWidgets.QAction(comicdl)
        self.actionExit.setObjectName("actionExit")
        self.menuComic_DL.addAction(self.actionSetting)
        self.menuComic_DL.addAction(self.actionExit)
        self.menubar.addAction(self.menuComic_DL.menuAction())

        self.retranslateUi(comicdl)
        self.pushButton.clicked.connect(comicdl.startDl) # type: ignore
        self.toch.returnPressed.connect(comicdl.startDl) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(comicdl)
        comicdl.setTabOrder(self.lineEdit_2, self.lineEdit)
        comicdl.setTabOrder(self.lineEdit, self.fromch)
        comicdl.setTabOrder(self.fromch, self.toch)
        comicdl.setTabOrder(self.toch, self.pushButton)

    def retranslateUi(self, comicdl):
        _translate = QtCore.QCoreApplication.translate
        comicdl.setWindowTitle(_translate("comicdl", "MainWindow"))
        self.label_4.setText(_translate("comicdl", "Name:"))
        self.label.setText(_translate("comicdl", "Link:"))
        self.label_2.setText(_translate("comicdl", "From Chapter:"))
        self.label_3.setText(_translate("comicdl", "To Chapter"))
        self.pushButton.setText(_translate("comicdl", "Download"))
        self.menuComic_DL.setTitle(_translate("comicdl", "Comic DL"))
        self.actionSetting.setText(_translate("comicdl", "Setting"))
        self.actionExit.setText(_translate("comicdl", "Exit"))
