# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setting(object):
    def setupUi(self, setting):
        setting.setObjectName("setting")
        setting.resize(335, 126)
        self.centralwidget = QtWidgets.QWidget(setting)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        setting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(setting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 335, 25))
        self.menubar.setObjectName("menubar")
        setting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(setting)
        self.statusbar.setObjectName("statusbar")
        setting.setStatusBar(self.statusbar)

        self.retranslateUi(setting)
        self.comboBox.currentIndexChanged['int'].connect(setting.changeSites) # type: ignore
        self.pushButton.clicked.connect(setting.savesetting) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(setting)

    def retranslateUi(self, setting):
        _translate = QtCore.QCoreApplication.translate
        setting.setWindowTitle(_translate("setting", "MainWindow"))
        self.label.setText(_translate("setting", "Sites:"))
        self.comboBox.setItemText(0, _translate("setting", "MangaTx.com"))
        self.comboBox.setItemText(1, _translate("setting", "1stKissManga.io"))
        self.comboBox.setItemText(2, _translate("setting", "Readm.org"))
        self.pushButton.setText(_translate("setting", "Ok"))
